### ISSUE TITLE
[PE-D][Tester E] UG: `ecreate` Feature parameter format unclear

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#144]
### Description
Under the `features`/Creating an event: `ecreate` section of the UG, the `r/` parameter is specified as:

> r/ - Roles needed for the event and its quantity

when the actual format is:

> The role argument must be an integer, followed by a space, and then the name of role required.

Furthermore, it isn't immediately obvious what the format for this parameter should be.

Same goes for the `m/` parameter.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: keaganpzh/ped#1

**Comment by brein62** [comment]
To update with more details
