### ISSUE TITLE
[PE-D][Tester B] Wrong error message for vdelete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-4/tp#147]
Input: vdelete 0, vdelete -20

Expected error message:
The volunteer index provided is invalid

Actual error message: 
Invalid command format! 
vdelete: Deletes the volunteer identified by the index number used in the displayed volunteer list.
Parameters: INDEX (must be a positive integer)
Example: vdelete 1

Description:
0 and -20 (negative 20) are numbers, although not positive integers. Error message for indexes out of valid range should be the same.

![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/426f8d0b-49e6-4552-8be9-bd2a338894f2.png)

![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/9f55f45b-0120-4d8f-97c0-b68f7487aec5.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Gavino3o/ped#1

**Comment by brein62** [comment]
Shouldn't have to address (code-wise) since 0 and -20 aren't positive integers, but will see if we can make UG more clear about this!
