### ISSUE TITLE
[PE-D][Tester A] Unable to add volunteer with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-4/tp#162]
Users cannot add two volunteers with the same name even if their phone numbers and emails are different.  

This design doesn't count in a very common situation in real life that people have the same name. It would be really troublesome for the coordinator to use this app if they cannot create profiles and distinguish two people only because they have the same name.

**_Unable to add volunteer with same name even if other fields are different:_**

![image.png](https://raw.githubusercontent.com/A1WAYSD/ped/main/files/988053a4-c8eb-48a5-aaa0-59e029f8bc83.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: A1WAYSD/ped#5

**Comment by brein62** [comment]
Issue to be addressed in future releases - name is currently an identity field as of v1.3 (and we're expecting that people will use identifiers as well).
