### ISSUE TITLE
[PE-D][Tester B] efind accepts invalid inputs in preamble

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-4/tp#164]
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/014f072a-7b46-4348-bece-918895049d7a.png)

Input:
`efind randomwordshere n/event1 n/anotherevent`

Expected:
An "invalid format" error message should be shown.

Actual:
for `efind` command, when there is random input (whether alphanumerical or not) in the preamble, the command still parses and executes.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Gavino3o/ped#6

**Comment by brein62** [comment]
Refer to #167.
