### ISSUE TITLE
[PE-D][Tester B] Typo in command summary for vcreate

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-4/tp#170]
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/4d61d8bd-1d4d-40fb-9adc-0d3c47ebfae5.png)

Invalid example command.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Gavino3o/ped#8

**Comment by brein62** [comment]
Duplicate of #194.
