### ISSUE TITLE
[PE-D][Tester B] Confusing terminology for event id

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#174]
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/1a75f7fd-7a37-4412-9c55-4dc5e5083718.png)

The use of "Event_ID" may confuse new users. Recommend changing event id to event index instead.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Gavino3o/ped#10

**Comment by brein62** [comment]
Good suggestion for clarity! To update in UG

**Comment by ruo-x** [comment]
will update all EVENT_ID, VOLUNTEER_ID to EVENT_INDEX, VOLUNTEER_INDEX
