### ISSUE TITLE
[PE-D][Tester B] clear not updated to vclear and eclear

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#179]
![image.png](https://raw.githubusercontent.com/Gavino3o/ped/main/files/b8425227-97c8-435f-9525-6f34bc318ff7.png)

Should be updated to vclear and eclear

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Gavino3o/ped#12

**Comment by brein62** [comment]
To fix

**Comment by brein62** [comment]
TODO: remove vclear feature
