### ISSUE TITLE
[PE-D][Tester C] Duplicate volunteers?

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#184]
I saw that you can't add a duplicate person with the same name. But it works if the name isn't capitalised. 

![image.png](https://raw.githubusercontent.com/Respirayson/ped/main/files/d966d728-e6cc-414a-8479-c3492b1b81f5.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Respirayson/ped#11

**Comment by brein62** [comment]
To make more clear in UG

**Comment by ruo-x** [comment]
i think q easy tho we can use the equalIgnoreCase to compare the names

**Comment by zacwong2151** [comment]
I made it such that 
- duplicate volunteers are: volunteers with same email or same phone number (because email and phone number are unique)
- they are not: volunteers with same name (because multiple people can have the same name)
