### ISSUE TITLE
[PE-D][Tester C] UG discrepancy in command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-4/tp#185]
The commands are already built. This is in the Editing the data file section.

![image.png](https://raw.githubusercontent.com/Respirayson/ped/main/files/f4c9052e-74ee-4445-b7b9-6f6a86ddcdb2.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Respirayson/ped#12

**Comment by brein62** [comment]
To fix in UG
